name: Build React App (class-exercise05)

on:
  workflow_dispatch:
  push:
    branches:
      - dep-inclusions

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Class Exercises/class-exercise05
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
